[phases.setup]
nixPkgs = ["php83", "php83Packages.composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-interaction"]

[phases.build]
cmds = [
    "php artisan config:clear",
    "php artisan view:clear",
    "php artisan cache:clear"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"